// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package positions

import (
	"encoding/json"
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetCrossMarginRiskLimitResp struct for GetCrossMarginRiskLimitResp
type GetCrossMarginRiskLimitResp struct {
	// common response
	CommonResponse *types.RestResponse
	Data           []GetCrossMarginRiskLimitData `json:"data,omitempty"`
}

// NewGetCrossMarginRiskLimitResp instantiates a new GetCrossMarginRiskLimitResp object
// This constructor will assign default values to properties that have it defined
func NewGetCrossMarginRiskLimitResp(data []GetCrossMarginRiskLimitData) *GetCrossMarginRiskLimitResp {
	this := GetCrossMarginRiskLimitResp{}
	this.Data = data
	return &this
}

// NewGetCrossMarginRiskLimitRespWithDefaults instantiates a new GetCrossMarginRiskLimitResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetCrossMarginRiskLimitRespWithDefaults() *GetCrossMarginRiskLimitResp {
	this := GetCrossMarginRiskLimitResp{}
	return &this
}

func (o *GetCrossMarginRiskLimitResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize
}

func (o *GetCrossMarginRiskLimitResp) UnmarshalJSON(b []byte) error {
	err := json.Unmarshal(b, &o.Data)
	return err
}

func (o *GetCrossMarginRiskLimitResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
