// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package positions

import (
	"encoding/json"
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// ModifyMarginLeverageResp struct for ModifyMarginLeverageResp
type ModifyMarginLeverageResp struct {
	// common response
	CommonResponse *types.RestResponse
	Data           bool `json:"data,omitempty"`
}

// NewModifyMarginLeverageResp instantiates a new ModifyMarginLeverageResp object
// This constructor will assign default values to properties that have it defined
func NewModifyMarginLeverageResp(data bool) *ModifyMarginLeverageResp {
	this := ModifyMarginLeverageResp{}
	this.Data = data
	return &this
}

// NewModifyMarginLeverageRespWithDefaults instantiates a new ModifyMarginLeverageResp object
// This constructor will only assign default values to properties that have it defined,
func NewModifyMarginLeverageRespWithDefaults() *ModifyMarginLeverageResp {
	this := ModifyMarginLeverageResp{}
	return &this
}

func (o *ModifyMarginLeverageResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize
}

func (o *ModifyMarginLeverageResp) UnmarshalJSON(b []byte) error {
	err := json.Unmarshal(b, &o.Data)
	return err
}

func (o *ModifyMarginLeverageResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
