// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package deposit

import (
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetDepositAddressV1Resp struct for GetDepositAddressV1Resp
type GetDepositAddressV1Resp struct {
	// common response
	CommonResponse *types.RestResponse
	// Deposit address
	Address *string `json:"address,omitempty"`
	// Address remark. If there’s no remark, it is empty. When you withdraw from other platforms to KuCoin, you need to fill in memo(tag). Be careful: If you do not fill in memo(tag), your deposit may not be available.
	Memo *string `json:"memo,omitempty"`
	// The chainName of currency
	Chain *string `json:"chain,omitempty"`
	// The chainId of currency
	ChainId *string `json:"chainId,omitempty"`
	// Deposit account type: main (funding account), trade (spot trading account)
	To *string `json:"to,omitempty"`
	// currency
	Currency *string `json:"currency,omitempty"`
	// The token contract address.
	ContractAddress *string `json:"contractAddress,omitempty"`
}

// NewGetDepositAddressV1Resp instantiates a new GetDepositAddressV1Resp object
// This constructor will assign default values to properties that have it defined
func NewGetDepositAddressV1Resp() *GetDepositAddressV1Resp {
	this := GetDepositAddressV1Resp{}
	return &this
}

// NewGetDepositAddressV1RespWithDefaults instantiates a new GetDepositAddressV1Resp object
// This constructor will only assign default values to properties that have it defined,
func NewGetDepositAddressV1RespWithDefaults() *GetDepositAddressV1Resp {
	this := GetDepositAddressV1Resp{}
	return &this
}

func (o *GetDepositAddressV1Resp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["memo"] = o.Memo
	toSerialize["chain"] = o.Chain
	toSerialize["chainId"] = o.ChainId
	toSerialize["to"] = o.To
	toSerialize["currency"] = o.Currency
	toSerialize["contractAddress"] = o.ContractAddress
	return toSerialize
}

func (o *GetDepositAddressV1Resp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
