// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package deposit

// GetDepositAddressV3Data struct for GetDepositAddressV3Data
type GetDepositAddressV3Data struct {
	// Deposit address
	Address string `json:"address,omitempty"`
	// Address remark. If there’s no remark, it is empty. When you withdraw from other platforms to KuCoin, you need to fill in memo(tag). Be careful: If you do not fill in memo(tag), your deposit may not be available.
	Memo string `json:"memo,omitempty"`
	// The chainId of currency
	ChainId string `json:"chainId,omitempty"`
	// Deposit account type: MAIN (funding account), TRADE (spot trading account)
	To string `json:"to,omitempty"`
	// Expiration time; Lightning network expiration time; this field is not applicable to non-Lightning networks
	ExpirationDate int32 `json:"expirationDate,omitempty"`
	// currency
	Currency string `json:"currency,omitempty"`
	// The token contract address.
	ContractAddress string `json:"contractAddress,omitempty"`
	// The chainName of currency
	ChainName string `json:"chainName,omitempty"`
	Remark string `json:"remark,omitempty"`
}

// NewGetDepositAddressV3Data instantiates a new GetDepositAddressV3Data object
// This constructor will assign default values to properties that have it defined
func NewGetDepositAddressV3Data(address string, memo string, chainId string, to string, expirationDate int32, currency string, contractAddress string, chainName, remark string) *GetDepositAddressV3Data {
	this := GetDepositAddressV3Data{}
	this.Address = address
	this.Memo = memo
	this.ChainId = chainId
	this.To = to
	this.ExpirationDate = expirationDate
	this.Currency = currency
	this.ContractAddress = contractAddress
	this.ChainName = chainName
	this.Remark = remark
	return &this
}

// NewGetDepositAddressV3DataWithDefaults instantiates a new GetDepositAddressV3Data object
// This constructor will only assign default values to properties that have it defined,
func NewGetDepositAddressV3DataWithDefaults() *GetDepositAddressV3Data {
	this := GetDepositAddressV3Data{}
	return &this
}

func (o *GetDepositAddressV3Data) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["address"] = o.Address
	toSerialize["memo"] = o.Memo
	toSerialize["chainId"] = o.ChainId
	toSerialize["to"] = o.To
	toSerialize["expirationDate"] = o.ExpirationDate
	toSerialize["currency"] = o.Currency
	toSerialize["contractAddress"] = o.ContractAddress
	toSerialize["chainName"] = o.ChainName
	toSerialize["remark"] = o.Remark
	return toSerialize
}
