// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package spotpublic

import (
	"encoding/json"
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// OrderbookLevel50Event struct for OrderbookLevel50Event
type OrderbookLevel50Event struct {
	// common response
	CommonResponse *types.WsMessage
	// price, size
	Asks      [][]string `json:"asks,omitempty"`
	Bids      [][]string `json:"bids,omitempty"`
	Timestamp int64      `json:"timestamp,omitempty"`
}

// NewOrderbookLevel50Event instantiates a new OrderbookLevel50Event object
// This constructor will assign default values to properties that have it defined
func NewOrderbookLevel50Event(asks [][]string, bids [][]string, timestamp int64) *OrderbookLevel50Event {
	this := OrderbookLevel50Event{}
	this.Asks = asks
	this.Bids = bids
	this.Timestamp = timestamp
	return &this
}

// NewOrderbookLevel50EventWithDefaults instantiates a new OrderbookLevel50Event object
// This constructor will only assign default values to properties that have it defined,
func NewOrderbookLevel50EventWithDefaults() *OrderbookLevel50Event {
	this := OrderbookLevel50Event{}
	return &this
}

func (o *OrderbookLevel50Event) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["asks"] = o.Asks
	toSerialize["bids"] = o.Bids
	toSerialize["timestamp"] = o.Timestamp
	return toSerialize
}

type OrderbookLevel50EventCallback func(topic string, subject string, data *OrderbookLevel50Event) error

type OrderbookLevel50EventCallbackWrapper struct {
	callback OrderbookLevel50EventCallback
}

func (w *OrderbookLevel50EventCallbackWrapper) OnMessage(msg *types.WsMessage) error {
	obj := &OrderbookLevel50Event{}
	err := json.Unmarshal(msg.RawData, obj)
	if err != nil {
		return err
	}
	obj.CommonResponse = msg
	return w.callback(msg.Topic, msg.Subject, obj)
}
