// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package spotpublic

import (
	"encoding/json"
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// CallAuctionInfoEvent struct for CallAuctionInfoEvent
type CallAuctionInfoEvent struct {
	// common response
	CommonResponse *types.WsMessage
	// Symbol
	Symbol string `json:"symbol,omitempty"`
	// Estimated price
	EstimatedPrice string `json:"estimatedPrice,omitempty"`
	// Estimated size
	EstimatedSize string `json:"estimatedSize,omitempty"`
	// Sell ​​order minimum price
	SellOrderRangeLowPrice string `json:"sellOrderRangeLowPrice,omitempty"`
	// Sell ​​order maximum price
	SellOrderRangeHighPrice string `json:"sellOrderRangeHighPrice,omitempty"`
	// Buy ​​order minimum price
	BuyOrderRangeLowPrice string `json:"buyOrderRangeLowPrice,omitempty"`
	// Buy ​​order maximum price
	BuyOrderRangeHighPrice string `json:"buyOrderRangeHighPrice,omitempty"`
	// Timestamp (ms)
	Time int64 `json:"time,omitempty"`
}

// NewCallAuctionInfoEvent instantiates a new CallAuctionInfoEvent object
// This constructor will assign default values to properties that have it defined
func NewCallAuctionInfoEvent(symbol string, estimatedPrice string, estimatedSize string, sellOrderRangeLowPrice string, sellOrderRangeHighPrice string, buyOrderRangeLowPrice string, buyOrderRangeHighPrice string, time int64) *CallAuctionInfoEvent {
	this := CallAuctionInfoEvent{}
	this.Symbol = symbol
	this.EstimatedPrice = estimatedPrice
	this.EstimatedSize = estimatedSize
	this.SellOrderRangeLowPrice = sellOrderRangeLowPrice
	this.SellOrderRangeHighPrice = sellOrderRangeHighPrice
	this.BuyOrderRangeLowPrice = buyOrderRangeLowPrice
	this.BuyOrderRangeHighPrice = buyOrderRangeHighPrice
	this.Time = time
	return &this
}

// NewCallAuctionInfoEventWithDefaults instantiates a new CallAuctionInfoEvent object
// This constructor will only assign default values to properties that have it defined,
func NewCallAuctionInfoEventWithDefaults() *CallAuctionInfoEvent {
	this := CallAuctionInfoEvent{}
	return &this
}

func (o *CallAuctionInfoEvent) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["symbol"] = o.Symbol
	toSerialize["estimatedPrice"] = o.EstimatedPrice
	toSerialize["estimatedSize"] = o.EstimatedSize
	toSerialize["sellOrderRangeLowPrice"] = o.SellOrderRangeLowPrice
	toSerialize["sellOrderRangeHighPrice"] = o.SellOrderRangeHighPrice
	toSerialize["buyOrderRangeLowPrice"] = o.BuyOrderRangeLowPrice
	toSerialize["buyOrderRangeHighPrice"] = o.BuyOrderRangeHighPrice
	toSerialize["time"] = o.Time
	return toSerialize
}

type CallAuctionInfoEventCallback func(topic string, subject string, data *CallAuctionInfoEvent) error

type CallAuctionInfoEventCallbackWrapper struct {
	callback CallAuctionInfoEventCallback
}

func (w *CallAuctionInfoEventCallbackWrapper) OnMessage(msg *types.WsMessage) error {
	obj := &CallAuctionInfoEvent{}
	err := json.Unmarshal(msg.RawData, obj)
	if err != nil {
		return err
	}
	obj.CommonResponse = msg
	return w.callback(msg.Topic, msg.Subject, obj)
}
