// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package spotpublic

import (
	"encoding/json"
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// CallAuctionOrderbookLevel50Event struct for CallAuctionOrderbookLevel50Event
type CallAuctionOrderbookLevel50Event struct {
	// common response
	CommonResponse *types.WsMessage
	// price, size
	Asks      [][]string `json:"asks,omitempty"`
	Bids      [][]string `json:"bids,omitempty"`
	Timestamp int64      `json:"timestamp,omitempty"`
}

// NewCallAuctionOrderbookLevel50Event instantiates a new CallAuctionOrderbookLevel50Event object
// This constructor will assign default values to properties that have it defined
func NewCallAuctionOrderbookLevel50Event(asks [][]string, bids [][]string, timestamp int64) *CallAuctionOrderbookLevel50Event {
	this := CallAuctionOrderbookLevel50Event{}
	this.Asks = asks
	this.Bids = bids
	this.Timestamp = timestamp
	return &this
}

// NewCallAuctionOrderbookLevel50EventWithDefaults instantiates a new CallAuctionOrderbookLevel50Event object
// This constructor will only assign default values to properties that have it defined,
func NewCallAuctionOrderbookLevel50EventWithDefaults() *CallAuctionOrderbookLevel50Event {
	this := CallAuctionOrderbookLevel50Event{}
	return &this
}

func (o *CallAuctionOrderbookLevel50Event) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["asks"] = o.Asks
	toSerialize["bids"] = o.Bids
	toSerialize["timestamp"] = o.Timestamp
	return toSerialize
}

type CallAuctionOrderbookLevel50EventCallback func(topic string, subject string, data *CallAuctionOrderbookLevel50Event) error

type CallAuctionOrderbookLevel50EventCallbackWrapper struct {
	callback CallAuctionOrderbookLevel50EventCallback
}

func (w *CallAuctionOrderbookLevel50EventCallbackWrapper) OnMessage(msg *types.WsMessage) error {
	obj := &CallAuctionOrderbookLevel50Event{}
	err := json.Unmarshal(msg.RawData, obj)
	if err != nil {
		return err
	}
	obj.CommonResponse = msg
	return w.callback(msg.Topic, msg.Subject, obj)
}
