// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package debit

import (
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// BorrowResp struct for BorrowResp
type BorrowResp struct {
	// common response
	CommonResponse *types.RestResponse
	// Borrow Order ID
	OrderNo string `json:"orderNo,omitempty"`
	// Actual borrowed amount
	ActualSize string `json:"actualSize,omitempty"`
}

// NewBorrowResp instantiates a new BorrowResp object
// This constructor will assign default values to properties that have it defined
func NewBorrowResp(orderNo string, actualSize string) *BorrowResp {
	this := BorrowResp{}
	this.OrderNo = orderNo
	this.ActualSize = actualSize
	return &this
}

// NewBorrowRespWithDefaults instantiates a new BorrowResp object
// This constructor will only assign default values to properties that have it defined,
func NewBorrowRespWithDefaults() *BorrowResp {
	this := BorrowResp{}
	return &this
}

func (o *BorrowResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["orderNo"] = o.OrderNo
	toSerialize["actualSize"] = o.ActualSize
	return toSerialize
}

func (o *BorrowResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
