// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package market

import (
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetCallAuctionPartOrderBookResp struct for GetCallAuctionPartOrderBookResp
type GetCallAuctionPartOrderBookResp struct {
	// common response
	CommonResponse *types.RestResponse
	// Timestamp (milliseconds)
	Time int64 `json:"time,omitempty"`
	// Sequence number
	Sequence string `json:"sequence,omitempty"`
	// bids, from high to low
	Bids [][]string `json:"bids,omitempty"`
	// asks, from low to high
	Asks [][]string `json:"asks,omitempty"`
}

// NewGetCallAuctionPartOrderBookResp instantiates a new GetCallAuctionPartOrderBookResp object
// This constructor will assign default values to properties that have it defined
func NewGetCallAuctionPartOrderBookResp(time int64, sequence string, bids [][]string, asks [][]string) *GetCallAuctionPartOrderBookResp {
	this := GetCallAuctionPartOrderBookResp{}
	this.Time = time
	this.Sequence = sequence
	this.Bids = bids
	this.Asks = asks
	return &this
}

// NewGetCallAuctionPartOrderBookRespWithDefaults instantiates a new GetCallAuctionPartOrderBookResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetCallAuctionPartOrderBookRespWithDefaults() *GetCallAuctionPartOrderBookResp {
	this := GetCallAuctionPartOrderBookResp{}
	return &this
}

func (o *GetCallAuctionPartOrderBookResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["time"] = o.Time
	toSerialize["sequence"] = o.Sequence
	toSerialize["bids"] = o.Bids
	toSerialize["asks"] = o.Asks
	return toSerialize
}

func (o *GetCallAuctionPartOrderBookResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
