// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package market

import (
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetCallAuctionInfoResp struct for GetCallAuctionInfoResp
type GetCallAuctionInfoResp struct {
	// common response
	CommonResponse *types.RestResponse
	// Symbol
	Symbol string `json:"symbol,omitempty"`
	// Estimated price
	EstimatedPrice string `json:"estimatedPrice,omitempty"`
	// Estimated size
	EstimatedSize string `json:"estimatedSize,omitempty"`
	// Sell ​​order minimum price
	SellOrderRangeLowPrice string `json:"sellOrderRangeLowPrice,omitempty"`
	// Sell ​​order maximum price
	SellOrderRangeHighPrice string `json:"sellOrderRangeHighPrice,omitempty"`
	// Buy order minimum price
	BuyOrderRangeLowPrice string `json:"buyOrderRangeLowPrice,omitempty"`
	// Buy ​​order maximum price
	BuyOrderRangeHighPrice string `json:"buyOrderRangeHighPrice,omitempty"`
	// Timestamp (ms)
	Time int64 `json:"time,omitempty"`
}

// NewGetCallAuctionInfoResp instantiates a new GetCallAuctionInfoResp object
// This constructor will assign default values to properties that have it defined
func NewGetCallAuctionInfoResp(symbol string, estimatedPrice string, estimatedSize string, sellOrderRangeLowPrice string, sellOrderRangeHighPrice string, buyOrderRangeLowPrice string, buyOrderRangeHighPrice string, time int64) *GetCallAuctionInfoResp {
	this := GetCallAuctionInfoResp{}
	this.Symbol = symbol
	this.EstimatedPrice = estimatedPrice
	this.EstimatedSize = estimatedSize
	this.SellOrderRangeLowPrice = sellOrderRangeLowPrice
	this.SellOrderRangeHighPrice = sellOrderRangeHighPrice
	this.BuyOrderRangeLowPrice = buyOrderRangeLowPrice
	this.BuyOrderRangeHighPrice = buyOrderRangeHighPrice
	this.Time = time
	return &this
}

// NewGetCallAuctionInfoRespWithDefaults instantiates a new GetCallAuctionInfoResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetCallAuctionInfoRespWithDefaults() *GetCallAuctionInfoResp {
	this := GetCallAuctionInfoResp{}
	return &this
}

func (o *GetCallAuctionInfoResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["symbol"] = o.Symbol
	toSerialize["estimatedPrice"] = o.EstimatedPrice
	toSerialize["estimatedSize"] = o.EstimatedSize
	toSerialize["sellOrderRangeLowPrice"] = o.SellOrderRangeLowPrice
	toSerialize["sellOrderRangeHighPrice"] = o.SellOrderRangeHighPrice
	toSerialize["buyOrderRangeLowPrice"] = o.BuyOrderRangeLowPrice
	toSerialize["buyOrderRangeHighPrice"] = o.BuyOrderRangeHighPrice
	toSerialize["time"] = o.Time
	return toSerialize
}

func (o *GetCallAuctionInfoResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
