// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package market

import (
	"encoding/json"
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetClientIPAddressResp struct for GetClientIPAddressResp
type GetClientIPAddressResp struct {
	// common response
	CommonResponse *types.RestResponse
	Data           string `json:"data,omitempty"`
}

// NewGetClientIPAddressResp instantiates a new GetClientIPAddressResp object
// This constructor will assign default values to properties that have it defined
func NewGetClientIPAddressResp(data string) *GetClientIPAddressResp {
	this := GetClientIPAddressResp{}
	this.Data = data
	return &this
}

// NewGetClientIPAddressRespWithDefaults instantiates a new GetClientIPAddressResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetClientIPAddressRespWithDefaults() *GetClientIPAddressResp {
	this := GetClientIPAddressResp{}
	return &this
}

func (o *GetClientIPAddressResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize
}

func (o *GetClientIPAddressResp) UnmarshalJSON(b []byte) error {
	err := json.Unmarshal(b, &o.Data)
	return err
}

func (o *GetClientIPAddressResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
