// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package service

import (
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/internal/interfaces"
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/generate/affiliate/affiliate"
)

type AffiliateService interface {

	// Get AffiliateAPI API
	GetAffiliateAPI() affiliate.AffiliateAPI
}

type AffiliateServiceImpl struct {
	AffiliateAPI affiliate.AffiliateAPI
}

func NewAffiliateService(transport interfaces.Transport) AffiliateService {
	api := &AffiliateServiceImpl{}
	api.AffiliateAPI = affiliate.NewAffiliateAPIImp(transport)
	return api
}

func (impl *AffiliateServiceImpl) GetAffiliateAPI() affiliate.AffiliateAPI {
	return impl.AffiliateAPI
}
