// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package order

import (
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// CancelOrderByClientOidOldResp struct for CancelOrderByClientOidOldResp
type CancelOrderByClientOidOldResp struct {
	// common response
	CommonResponse *types.RestResponse
	// Client Order Id，unique identifier created by the user
	ClientOid string `json:"clientOid,omitempty"`
	// The unique order id generated by the trading system
	CancelledOrderId     string   `json:"cancelledOrderId,omitempty"`
	CancelledOcoOrderIds []string `json:"cancelledOcoOrderIds,omitempty"`
}

// NewCancelOrderByClientOidOldResp instantiates a new CancelOrderByClientOidOldResp object
// This constructor will assign default values to properties that have it defined
func NewCancelOrderByClientOidOldResp(clientOid string, cancelledOrderId string, cancelledOcoOrderIds []string) *CancelOrderByClientOidOldResp {
	this := CancelOrderByClientOidOldResp{}
	this.ClientOid = clientOid
	this.CancelledOrderId = cancelledOrderId
	this.CancelledOcoOrderIds = cancelledOcoOrderIds
	return &this
}

// NewCancelOrderByClientOidOldRespWithDefaults instantiates a new CancelOrderByClientOidOldResp object
// This constructor will only assign default values to properties that have it defined,
func NewCancelOrderByClientOidOldRespWithDefaults() *CancelOrderByClientOidOldResp {
	this := CancelOrderByClientOidOldResp{}
	return &this
}

func (o *CancelOrderByClientOidOldResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["clientOid"] = o.ClientOid
	toSerialize["cancelledOrderId"] = o.CancelledOrderId
	toSerialize["cancelledOcoOrderIds"] = o.CancelledOcoOrderIds
	return toSerialize
}

func (o *CancelOrderByClientOidOldResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
