// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package order

import (
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// ModifyOrderResp struct for ModifyOrderResp
type ModifyOrderResp struct {
	// common response
	CommonResponse *types.RestResponse
	// The new order ID
	NewOrderId string `json:"newOrderId,omitempty"`
	// The original client order ID
	ClientOid string `json:"clientOid,omitempty"`
}

// NewModifyOrderResp instantiates a new ModifyOrderResp object
// This constructor will assign default values to properties that have it defined
func NewModifyOrderResp(newOrderId string, clientOid string) *ModifyOrderResp {
	this := ModifyOrderResp{}
	this.NewOrderId = newOrderId
	this.ClientOid = clientOid
	return &this
}

// NewModifyOrderRespWithDefaults instantiates a new ModifyOrderResp object
// This constructor will only assign default values to properties that have it defined,
func NewModifyOrderRespWithDefaults() *ModifyOrderResp {
	this := ModifyOrderResp{}
	return &this
}

func (o *ModifyOrderResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["newOrderId"] = o.NewOrderId
	toSerialize["clientOid"] = o.ClientOid
	return toSerialize
}

func (o *ModifyOrderResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
