// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package order

import (
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetOpenOrdersByPageResp struct for GetOpenOrdersByPageResp
type GetOpenOrdersByPageResp struct {
	// common response
	CommonResponse *types.RestResponse
	CurrentPage    int32                      `json:"currentPage,omitempty"`
	PageSize       int32                      `json:"pageSize,omitempty"`
	TotalNum       int32                      `json:"totalNum,omitempty"`
	TotalPage      int32                      `json:"totalPage,omitempty"`
	Items          []GetOpenOrdersByPageItems `json:"items,omitempty"`
}

// NewGetOpenOrdersByPageResp instantiates a new GetOpenOrdersByPageResp object
// This constructor will assign default values to properties that have it defined
func NewGetOpenOrdersByPageResp(currentPage int32, pageSize int32, totalNum int32, totalPage int32, items []GetOpenOrdersByPageItems) *GetOpenOrdersByPageResp {
	this := GetOpenOrdersByPageResp{}
	this.CurrentPage = currentPage
	this.PageSize = pageSize
	this.TotalNum = totalNum
	this.TotalPage = totalPage
	this.Items = items
	return &this
}

// NewGetOpenOrdersByPageRespWithDefaults instantiates a new GetOpenOrdersByPageResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetOpenOrdersByPageRespWithDefaults() *GetOpenOrdersByPageResp {
	this := GetOpenOrdersByPageResp{}
	return &this
}

func (o *GetOpenOrdersByPageResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["currentPage"] = o.CurrentPage
	toSerialize["pageSize"] = o.PageSize
	toSerialize["totalNum"] = o.TotalNum
	toSerialize["totalPage"] = o.TotalPage
	toSerialize["items"] = o.Items
	return toSerialize
}

func (o *GetOpenOrdersByPageResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
