// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package ndbroker

import (
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetKYCStatusListResp struct for GetKYCStatusListResp
type GetKYCStatusListResp struct {
	// common response
	CommonResponse *types.RestResponse
	CurrentPage    int32                   `json:"currentPage,omitempty"`
	PageSize       int32                   `json:"pageSize,omitempty"`
	TotalNum       int32                   `json:"totalNum,omitempty"`
	TotalPage      int32                   `json:"totalPage,omitempty"`
	Items          []GetKYCStatusListItems `json:"items,omitempty"`
}

// NewGetKYCStatusListResp instantiates a new GetKYCStatusListResp object
// This constructor will assign default values to properties that have it defined
func NewGetKYCStatusListResp(currentPage int32, pageSize int32, totalNum int32, totalPage int32, items []GetKYCStatusListItems) *GetKYCStatusListResp {
	this := GetKYCStatusListResp{}
	this.CurrentPage = currentPage
	this.PageSize = pageSize
	this.TotalNum = totalNum
	this.TotalPage = totalPage
	this.Items = items
	return &this
}

// NewGetKYCStatusListRespWithDefaults instantiates a new GetKYCStatusListResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetKYCStatusListRespWithDefaults() *GetKYCStatusListResp {
	this := GetKYCStatusListResp{}
	return &this
}

func (o *GetKYCStatusListResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["currentPage"] = o.CurrentPage
	toSerialize["pageSize"] = o.PageSize
	toSerialize["totalNum"] = o.TotalNum
	toSerialize["totalPage"] = o.TotalPage
	toSerialize["items"] = o.Items
	return toSerialize
}

func (o *GetKYCStatusListResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
