// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package ndbroker

import (
	"encoding/json"
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetKYCStatusResp struct for GetKYCStatusResp
type GetKYCStatusResp struct {
	// common response
	CommonResponse *types.RestResponse
	Data           []GetKYCStatusData `json:"data,omitempty"`
}

// NewGetKYCStatusResp instantiates a new GetKYCStatusResp object
// This constructor will assign default values to properties that have it defined
func NewGetKYCStatusResp(data []GetKYCStatusData) *GetKYCStatusResp {
	this := GetKYCStatusResp{}
	this.Data = data
	return &this
}

// NewGetKYCStatusRespWithDefaults instantiates a new GetKYCStatusResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetKYCStatusRespWithDefaults() *GetKYCStatusResp {
	this := GetKYCStatusResp{}
	return &this
}

func (o *GetKYCStatusResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize
}

func (o *GetKYCStatusResp) UnmarshalJSON(b []byte) error {
	err := json.Unmarshal(b, &o.Data)
	return err
}

func (o *GetKYCStatusResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
