// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package subaccount

import (
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// AddSubAccountResp struct for AddSubAccountResp
type AddSubAccountResp struct {
	// common response
	CommonResponse *types.RestResponse
	// Sub account user id
	Uid int32 `json:"uid,omitempty"`
	// Sub account name
	SubName string `json:"subName,omitempty"`
	// Sub account name
	Remarks string `json:"remarks,omitempty"`
	// permission
	Access string `json:"access,omitempty"`
}

// NewAddSubAccountResp instantiates a new AddSubAccountResp object
// This constructor will assign default values to properties that have it defined
func NewAddSubAccountResp(uid int32, subName string, remarks string, access string) *AddSubAccountResp {
	this := AddSubAccountResp{}
	this.Uid = uid
	this.SubName = subName
	this.Remarks = remarks
	this.Access = access
	return &this
}

// NewAddSubAccountRespWithDefaults instantiates a new AddSubAccountResp object
// This constructor will only assign default values to properties that have it defined,
func NewAddSubAccountRespWithDefaults() *AddSubAccountResp {
	this := AddSubAccountResp{}
	return &this
}

func (o *AddSubAccountResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["uid"] = o.Uid
	toSerialize["subName"] = o.SubName
	toSerialize["remarks"] = o.Remarks
	toSerialize["access"] = o.Access
	return toSerialize
}

func (o *AddSubAccountResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
