// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package account

import (
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetFuturesAccountResp struct for GetFuturesAccountResp
type GetFuturesAccountResp struct {
	// common response
	CommonResponse *types.RestResponse
	// Account equity = marginBalance + unrealizedPNL
	AccountEquity float64 `json:"accountEquity,omitempty"`
	// Unrealized profit and loss
	UnrealisedPNL float64 `json:"unrealisedPNL,omitempty"`
	// Margin balance = positionMargin + orderMargin + frozenFunds + availableBalance - unrealizedPNL
	MarginBalance float64 `json:"marginBalance,omitempty"`
	// Position margin
	PositionMargin float64 `json:"positionMargin,omitempty"`
	// Order margin
	OrderMargin float64 `json:"orderMargin,omitempty"`
	// Frozen funds for out-transfer
	FrozenFunds float64 `json:"frozenFunds,omitempty"`
	// Available balance
	AvailableBalance float64 `json:"availableBalance,omitempty"`
	// Currency
	Currency string `json:"currency,omitempty"`
	// Cross margin risk rate
	RiskRatio float64 `json:"riskRatio,omitempty"`
	// Maximum amount that can be withdrawn/transferred.
	MaxWithdrawAmount float64 `json:"maxWithdrawAmount,omitempty"`
}

// NewGetFuturesAccountResp instantiates a new GetFuturesAccountResp object
// This constructor will assign default values to properties that have it defined
func NewGetFuturesAccountResp(accountEquity float64, unrealisedPNL float64, marginBalance float64, positionMargin float64, orderMargin float64, frozenFunds float64, availableBalance float64, currency string, riskRatio float64, maxWithdrawAmount float64) *GetFuturesAccountResp {
	this := GetFuturesAccountResp{}
	this.AccountEquity = accountEquity
	this.UnrealisedPNL = unrealisedPNL
	this.MarginBalance = marginBalance
	this.PositionMargin = positionMargin
	this.OrderMargin = orderMargin
	this.FrozenFunds = frozenFunds
	this.AvailableBalance = availableBalance
	this.Currency = currency
	this.RiskRatio = riskRatio
	this.MaxWithdrawAmount = maxWithdrawAmount
	return &this
}

// NewGetFuturesAccountRespWithDefaults instantiates a new GetFuturesAccountResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetFuturesAccountRespWithDefaults() *GetFuturesAccountResp {
	this := GetFuturesAccountResp{}
	return &this
}

func (o *GetFuturesAccountResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["accountEquity"] = o.AccountEquity
	toSerialize["unrealisedPNL"] = o.UnrealisedPNL
	toSerialize["marginBalance"] = o.MarginBalance
	toSerialize["positionMargin"] = o.PositionMargin
	toSerialize["orderMargin"] = o.OrderMargin
	toSerialize["frozenFunds"] = o.FrozenFunds
	toSerialize["availableBalance"] = o.AvailableBalance
	toSerialize["currency"] = o.Currency
	toSerialize["riskRatio"] = o.RiskRatio
	toSerialize["maxWithdrawAmount"] = o.MaxWithdrawAmount
	return toSerialize
}

func (o *GetFuturesAccountResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
