// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package viplending

import (
	"context"
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/internal/interfaces"
)

type VIPLendingAPI interface {

	// GetDiscountRateConfigs Get Discount Rate Configs
	// Description: Get the gradient discount rate of each currency
	// Documentation: https://www.kucoin.com/docs-new/api-3471463
	// +-----------------------+---------+
	// | Extra API Info        | Value   |
	// +-----------------------+---------+
	// | API-DOMAIN            | SPOT    |
	// | API-CHANNEL           | PRIVATE |
	// | API-PERMISSION        | NULL    |
	// | API-RATE-LIMIT-POOL   | PUBLIC  |
	// | API-RATE-LIMIT-WEIGHT | 10      |
	// +-----------------------+---------+
	GetDiscountRateConfigs(ctx context.Context) (*GetDiscountRateConfigsResp, error)

	// GetLoanInfo Get Loan Info
	// Description: The following information is only applicable to loans.  Get information on off-exchange funding and loans. This endpoint is only for querying accounts that are currently involved in loans.
	// Documentation: https://www.kucoin.com/docs-new/api-3470277
	// +-----------------------+------------+
	// | Extra API Info        | Value      |
	// +-----------------------+------------+
	// | API-DOMAIN            | SPOT       |
	// | API-CHANNEL           | PRIVATE    |
	// | API-PERMISSION        | SPOT       |
	// | API-RATE-LIMIT-POOL   | MANAGEMENT |
	// | API-RATE-LIMIT-WEIGHT | 5          |
	// +-----------------------+------------+
	GetLoanInfo(ctx context.Context) (*GetLoanInfoResp, error)

	// GetAccounts Get Accounts
	// Description: Accounts participating in OTC lending. This interface is only for querying accounts currently running OTC lending.
	// Documentation: https://www.kucoin.com/docs-new/api-3470278
	// +-----------------------+------------+
	// | Extra API Info        | Value      |
	// +-----------------------+------------+
	// | API-DOMAIN            | SPOT       |
	// | API-CHANNEL           | PRIVATE    |
	// | API-PERMISSION        | SPOT       |
	// | API-RATE-LIMIT-POOL   | MANAGEMENT |
	// | API-RATE-LIMIT-WEIGHT | 20         |
	// +-----------------------+------------+
	GetAccounts(ctx context.Context) (*GetAccountsResp, error)
}

type VIPLendingAPIImpl struct {
	transport interfaces.Transport
}

func NewVIPLendingAPIImp(transport interfaces.Transport) *VIPLendingAPIImpl {
	return &VIPLendingAPIImpl{transport: transport}
}

func (impl *VIPLendingAPIImpl) GetDiscountRateConfigs(ctx context.Context) (*GetDiscountRateConfigsResp, error) {
	resp := &GetDiscountRateConfigsResp{}
	err := impl.transport.Call(ctx, "spot", false, "Get", "/api/v1/otc-loan/discount-rate-configs", nil, resp, false)
	return resp, err
}

func (impl *VIPLendingAPIImpl) GetLoanInfo(ctx context.Context) (*GetLoanInfoResp, error) {
	resp := &GetLoanInfoResp{}
	err := impl.transport.Call(ctx, "spot", false, "Get", "/api/v1/otc-loan/loan", nil, resp, false)
	return resp, err
}

func (impl *VIPLendingAPIImpl) GetAccounts(ctx context.Context) (*GetAccountsResp, error) {
	resp := &GetAccountsResp{}
	err := impl.transport.Call(ctx, "spot", false, "Get", "/api/v1/otc-loan/accounts", nil, resp, false)
	return resp, err
}
