// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package viplending

import (
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetLoanInfoResp struct for GetLoanInfoResp
type GetLoanInfoResp struct {
	// common response
	CommonResponse *types.RestResponse
	// Master UID
	ParentUid string `json:"parentUid,omitempty"`
	// Loan Orders
	Orders []GetLoanInfoOrders `json:"orders,omitempty"`
	Ltv    GetLoanInfoLtv      `json:"ltv,omitempty"`
	// Total Margin Amount (USDT)
	TotalMarginAmount string `json:"totalMarginAmount,omitempty"`
	// Total Maintenance Margin for Restricted Transfers (USDT)
	TransferMarginAmount string               `json:"transferMarginAmount,omitempty"`
	Margins              []GetLoanInfoMargins `json:"margins,omitempty"`
}

// NewGetLoanInfoResp instantiates a new GetLoanInfoResp object
// This constructor will assign default values to properties that have it defined
func NewGetLoanInfoResp(parentUid string, orders []GetLoanInfoOrders, ltv GetLoanInfoLtv, totalMarginAmount string, transferMarginAmount string, margins []GetLoanInfoMargins) *GetLoanInfoResp {
	this := GetLoanInfoResp{}
	this.ParentUid = parentUid
	this.Orders = orders
	this.Ltv = ltv
	this.TotalMarginAmount = totalMarginAmount
	this.TransferMarginAmount = transferMarginAmount
	this.Margins = margins
	return &this
}

// NewGetLoanInfoRespWithDefaults instantiates a new GetLoanInfoResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetLoanInfoRespWithDefaults() *GetLoanInfoResp {
	this := GetLoanInfoResp{}
	return &this
}

func (o *GetLoanInfoResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["parentUid"] = o.ParentUid
	toSerialize["orders"] = o.Orders
	toSerialize["ltv"] = o.Ltv
	toSerialize["totalMarginAmount"] = o.TotalMarginAmount
	toSerialize["transferMarginAmount"] = o.TransferMarginAmount
	toSerialize["margins"] = o.Margins
	return toSerialize
}

func (o *GetLoanInfoResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
