// Code generated by Kucoin Universal SDK Generator; DO NOT EDIT.

package viplending

import (
	"encoding/json"
	"github.com/serenite11/kucoin-universal-sdk/sdk/golang/pkg/types"
)

// GetDiscountRateConfigsResp struct for GetDiscountRateConfigsResp
type GetDiscountRateConfigsResp struct {
	// common response
	CommonResponse *types.RestResponse
	Data           []GetDiscountRateConfigsData `json:"data,omitempty"`
}

// NewGetDiscountRateConfigsResp instantiates a new GetDiscountRateConfigsResp object
// This constructor will assign default values to properties that have it defined
func NewGetDiscountRateConfigsResp(data []GetDiscountRateConfigsData) *GetDiscountRateConfigsResp {
	this := GetDiscountRateConfigsResp{}
	this.Data = data
	return &this
}

// NewGetDiscountRateConfigsRespWithDefaults instantiates a new GetDiscountRateConfigsResp object
// This constructor will only assign default values to properties that have it defined,
func NewGetDiscountRateConfigsRespWithDefaults() *GetDiscountRateConfigsResp {
	this := GetDiscountRateConfigsResp{}
	return &this
}

func (o *GetDiscountRateConfigsResp) ToMap() map[string]interface{} {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize
}

func (o *GetDiscountRateConfigsResp) UnmarshalJSON(b []byte) error {
	err := json.Unmarshal(b, &o.Data)
	return err
}

func (o *GetDiscountRateConfigsResp) SetCommonResponse(response *types.RestResponse) {
	o.CommonResponse = response
}
